zuul:
  #ignored-services: '*'
  routes:
    reservations:
      path: /reservation-service/**
      serviceId: reservation-service
  #prefix: /api


server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
